username: "" # User name for CDSE
password: "" # Password for CDSE
output_dir: "" # Directory you want to write files and products to
polygon_wkt: |
  POLYGON (
    (-20.263238824222373 84.8852877777822, 
     -36.25445787748578 67.02581594412311, 
     11.148084316116405 52.31593720759386, 
     45.98609725358305 63.94940066151824, 
     89.96194965005743 84.8341192704811, 
     -20.263238824222373 84.8852877777822)

valid_satellites:
  - S1
  - S2L1C
  - S2L2A
  - S3
  - all